// Generated by CoffeeScript 1.7.1
(function() {
  var Command;

  Command = (function() {
    Command.prototype.command = null;

    Command.prototype.args = [];

    function Command(command, args) {
      this.command = command;
      this.args = args;
    }

    return Command;

  })();

  Command.parse = function(data) {
    var args, parts;
    parts = data.trim().split(new RegExp("/ :/"));
    args = parts[0].split(' ');
    parts = [parts.shift(), parts.join(' :')];
    if (parts.length > 0) {
      args.push(parts[1]);
    }
    if (data.match(/^:/)) {
      args[1] = args.splice(0, 1, args[1]);
      args[1] = (args[1] + '').replace(/^:/, '');
    }
    return new Command(args[0].toUpperCase(), args.slice(1));
  };

  exports.Command = Command;

}).call(this);
