// Generated by CoffeeScript 1.6.2
(function() {
  var Campfire, Rooms, configuration, fs;

  fs = require("fs");

  Campfire = require("campfire").Campfire;

  configuration = JSON.parse(fs.readFileSync("./config/config.json").toString());

  Rooms = (function() {
    Rooms.prototype.campfire = new Campfire({
      ssl: true,
      token: configuration.token,
      account: configuration.subdomain
    });

    Rooms.prototype.rooms = [];

    function Rooms() {
      this._sync();
    }

    Rooms.prototype._sync = function() {
      var _this = this;

      return this.campfire.rooms(function(err, all_rooms) {
        var room, _i, _len, _results;

        _results = [];
        for (_i = 0, _len = all_rooms.length; _i < _len; _i++) {
          room = all_rooms[_i];
          _results.push(_this.campfire.room(room.id, function(err, r) {
            return _this.rooms.push(r);
          }));
        }
        return _results;
      });
    };

    return Rooms;

  })();

  exports.Rooms = Rooms;

}).call(this);
